-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: [--disable=missing-docstring, --disable=C, --disable=W, --disable=R]

